name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # Windows - MSVC
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          # Linux - GCC
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          # macOS - Clang
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev libx11-dev xorg-dev

    - name: Configure Client CMake
      run: >
        cmake -B ${{ github.workspace }}/client/build
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=Release
        -S ${{ github.workspace }}/client

    - name: Build and Test Client
      run: cmake --build ${{ github.workspace }}/client/build --config Release --target client_build_test

    - name: Configure Server CMake
      run: >
        cmake -B ${{ github.workspace }}/server/build
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=Release
        -S ${{ github.workspace }}/server

    - name: Build and Test Server
      run: cmake --build ${{ github.workspace }}/server/build --config Release --target server_build_test
